import {ENGINES,TYPES,clone,uid,escapeHTML as h,validateQuestion,validateData} from './data.js';
import {configured,demo,loadAdmin,saveAdmin,login,logout,getSession,signup,recover,updatePassword,acceptCallback} from './api.js';
const $=s=>document.querySelector(s), form=$('#question-form');
let data,revision=0,busy=false,dirty=false,deleteId=null,imported=null;
function status(message,error=false){$('#global-status').textContent=message;$('#global-status').style.color=error?'var(--danger)':'var(--green)';}
function error(message){$('#form-error').hidden=false;$('#form-error').textContent=message;$('#form-error').focus();}
function currentEngine(){return data.types.find(t=>t.id===$('#question-type').value)?.engine||'single';}
function selectedID(){return form.elements.id.value;}
function fillTypes(){const selected=$('#question-type').value,filter=$('#filter-type').value;const options=data.types.map(t=>`<option value="${h(t.id)}">${h(t.label)}</option>`).join('');$('#question-type').innerHTML=options;$('#filter-type').innerHTML='<option value="">Tất cả dạng câu hỏi</option>'+options;if(data.types.some(t=>t.id===selected))$('#question-type').value=selected;$('#filter-type').value=filter;$('#custom-types').innerHTML=data.types.filter(t=>!TYPES.some(b=>b.id===t.id)).map(t=>`<span class="pill">${h(t.label)} · ${h(ENGINES[t.engine])}</span>`).join('');}
function choiceRow(text,index,correct,engine){return `<div class="choice-row"><span>${String.fromCharCode(65+index)}</span><input type="text" class="choice-text" value="${h(text)}" maxlength="4000" aria-label="Nội dung lựa chọn ${index+1}" required><label class="choice-correct" title="Đánh dấu đáp án đúng"><input type="${engine==='single'?'radio':'checkbox'}" name="correct-choice" value="${index}" aria-label="Lựa chọn ${index+1} là đáp án đúng" ${correct?'checked':''}></label>${engine==='multiple'?`<button type="button" class="quiet remove-choice" aria-label="Xóa lựa chọn ${index+1}">×</button>`:''}</div>`;}
function fields(q={}){
 const engine=currentEngine();let html='';
 if(['single','multiple'].includes(engine)) {const options=q.options||['','','',''];html=`<div class="field-box"><strong>Các lựa chọn và đáp án</strong><p>${engine==='single'?'Đánh dấu tròn bên phải cho một đáp án đúng.':'Đánh dấu ô bên phải cho tất cả đáp án đúng (2–12 lựa chọn).'}</p><div id="choices">${options.map((t,i)=>choiceRow(t,i,(q.correct||[]).includes(i),engine)).join('')}</div>${engine==='multiple'?'<button type="button" id="add-choice" class="secondary">+ Thêm lựa chọn</button>':''}</div>`;}
 if(engine==='boolean')html=`<fieldset class="field-box"><legend>Đáp án đúng</legend><label class="check-label"><input type="radio" name="boolean-answer" value="true" ${q.answer!==false?'checked':''}>Đúng</label><label class="check-label"><input type="radio" name="boolean-answer" value="false" ${q.answer===false?'checked':''}>Sai</label></fieldset>`;
 if(engine==='fill')html=`<div class="field-box"><label>Đoạn văn có chỗ trống<textarea id="fill-template" rows="3" maxlength="4000" required placeholder="Lạy Cha chúng con ở trên {{…}}">${h(q.template||'')}</textarea></label><p>Dùng chính xác <code>{{…}}</code> cho mỗi chỗ trống. <button type="button" id="insert-blank" class="secondary">Chèn chỗ trống</button></p><label>Đáp án từng chỗ trống<textarea id="fill-answers" rows="3" required placeholder="Mỗi dòng là đáp án của một chỗ trống, theo thứ tự">${h((q.answers||[]).join('\n'))}</textarea></label><p>Số dòng đáp án phải bằng số chỗ trống.</p></div>`;
 if(engine==='match')html=`<div class="field-box"><strong>Các cặp nối đúng</strong><p>Mỗi dòng bên trái nối với dòng cùng vị trí bên phải. Khi trình chiếu, cột phải tự đảo thứ tự.</p><div class="form-grid"><label>Cột A<textarea id="match-left" rows="6" required placeholder="Mỗi dòng một nội dung">${h((q.pairs||[]).map(p=>p.left).join('\n'))}</textarea></label><label>Cột B (đáp án tương ứng)<textarea id="match-right" rows="6" required placeholder="Mỗi dòng một nội dung">${h((q.pairs||[]).map(p=>p.right).join('\n'))}</textarea></label></div></div>`;
 if(engine==='order')html=`<div class="field-box"><label>Các mục theo thứ tự ĐÚNG<textarea id="order-items" rows="6" required placeholder="Bước thứ nhất&#10;Bước thứ hai&#10;Bước thứ ba">${h((q.items||[]).join('\n'))}</textarea></label><p>Mỗi dòng một mục (2–12 mục). Website đảo thứ tự khi ra câu hỏi và xếp đúng khi hiện đáp án.</p></div>`;
 if(engine==='short')html=`<label>Đáp án mẫu<textarea id="short-answer" rows="3" maxlength="4000" required placeholder="Nhập câu trả lời sẽ được công bố">${h(q.answer||'')}</textarea></label>`;
 $('#type-fields').innerHTML=html;
 if($('#add-choice'))$('#add-choice').onclick=()=>{const rows=[...document.querySelectorAll('.choice-row')];if(rows.length>=12)return;$('#choices').insertAdjacentHTML('beforeend',choiceRow('',rows.length,false,'multiple'));dirty=true;};
 if($('#insert-blank'))$('#insert-blank').onclick=()=>{const t=$('#fill-template');t.setRangeText('{{…}}',t.selectionStart,t.selectionEnd,'end');t.focus();dirty=true;};
}
$('#type-fields').addEventListener('click',e=>{const button=e.target.closest('.remove-choice');if(!button)return;if(document.querySelectorAll('.choice-row').length<=2)return;button.closest('.choice-row').remove();document.querySelectorAll('.choice-row').forEach((row,i)=>{row.querySelector('span').textContent=String.fromCharCode(65+i);row.querySelector('[name="correct-choice"]').value=i;});dirty=true;});
function renderList(){
 const query=$('#search').value.trim().toLocaleLowerCase('vi'),filter=$('#filter-type').value;
 const entries=data.questions.map((q,i)=>({q,i})).filter(({q})=>(!query||q.prompt.toLocaleLowerCase('vi').includes(query))&&(!filter||q.type===filter));
 $('#library-count').textContent=`${data.questions.length} câu · ${data.questions.filter(q=>q.enabled).length} đang trình chiếu`;
 $('#no-results').hidden=entries.length>0;
 $('#question-list').innerHTML=entries.map(({q,i})=>`<li class="question-row${q.id===selectedID()?' editing':''}" data-id="${h(q.id)}"><div class="row-top"><span class="row-number">${i+1}</span><span class="row-title">${h(q.prompt)}</span></div><div class="row-meta"><span>${h(data.types.find(t=>t.id===q.type).label)}</span><span>${q.seconds} giây</span></div><div class="row-actions"><label class="check-label"><input type="checkbox" class="toggle-enabled" ${q.enabled?'checked':''} aria-label="Đưa câu ${i+1} lên trình chiếu">Hiển thị</label><button data-action="up" class="secondary" aria-label="Đưa câu ${i+1} lên" ${i===0?'disabled':''}>↑</button><button data-action="down" class="secondary" aria-label="Đưa câu ${i+1} xuống" ${i===data.questions.length-1?'disabled':''}>↓</button><input type="number" class="position" aria-label="Vị trí câu ${i+1}" min="1" max="${data.questions.length}" value="${i+1}"><button class="secondary" data-action="edit">Sửa</button><button class="quiet" data-action="delete">Xóa</button></div></li>`).join('');
}
function clearEditor(){form.reset();form.elements.id.value='';form.elements.seconds.value=30;form.elements.enabled.checked=true;$('#question-type').value='single';$('#editor-heading').textContent='Thêm câu hỏi';$('#editor-mode').textContent='BIÊN SOẠN';$('#form-error').hidden=true;fields();dirty=false;renderList();}
function canDiscard(){return !dirty||confirm('Bạn có nội dung chưa lưu. Bỏ các thay đổi này?');}
function edit(q){if(!canDiscard())return;form.elements.id.value=q.id;form.elements.type.value=q.type;form.elements.prompt.value=q.prompt;form.elements.seconds.value=q.seconds;form.elements.explanation.value=q.explanation;form.elements.enabled.checked=q.enabled;$('#editor-heading').textContent='Sửa câu hỏi';$('#editor-mode').textContent=`CÂU ${data.questions.findIndex(x=>x.id===q.id)+1}`;$('#form-error').hidden=true;fields(q);dirty=false;renderList();$('#editor-heading').scrollIntoView({block:'start',behavior:'instant'});form.elements.prompt.focus({preventScroll:true});}
async function persist(next,message){if(busy)throw new Error('Đang lưu, vui lòng chờ.');busy=true;const controls=[...document.querySelectorAll('#admin-content button,#admin-content input,#admin-content select,#admin-content textarea')];const prior=controls.map(x=>x.disabled);controls.forEach(x=>x.disabled=true);status('Đang lưu vào cơ sở dữ liệu…');try{revision=await saveAdmin(next,revision);data=next;status(message);return true;}catch(e){status(e.message,true);throw e;}finally{busy=false;controls.forEach((x,i)=>x.disabled=prior[i]);}}
const lines=selector=>$(selector).value.split('\n').map(x=>x.trim()).filter(Boolean);
form.addEventListener('input',()=>{dirty=true;});
$('#question-type').onchange=()=>{fields();dirty=true;};
form.onsubmit=async e=>{e.preventDefault();$('#form-error').hidden=true;const q={id:selectedID()||uid(),type:form.elements.type.value,prompt:form.elements.prompt.value.trim(),seconds:Number(form.elements.seconds.value),enabled:form.elements.enabled.checked,explanation:form.elements.explanation.value.trim()};const engine=currentEngine();
 if(['single','multiple'].includes(engine)){q.options=[...document.querySelectorAll('.choice-text')].map(x=>x.value.trim());q.correct=[...document.querySelectorAll('[name="correct-choice"]')].flatMap((x,i)=>x.checked?[i]:[]);}
 if(engine==='boolean')q.answer=$('[name="boolean-answer"]:checked').value==='true';
 if(engine==='fill'){q.template=$('#fill-template').value.trim();q.answers=lines('#fill-answers');}
 if(engine==='match'){const left=lines('#match-left'),right=lines('#match-right');if(left.length!==right.length)return error('Hai cột phải có cùng số dòng.');q.pairs=left.map((l,i)=>({left:l,right:right[i]}));}
 if(engine==='order')q.items=lines('#order-items');
 if(engine==='short')q.answer=$('#short-answer').value.trim();
 try{validateQuestion(q,data.types);const next=clone(data),i=next.questions.findIndex(x=>x.id===q.id);if(i<0)next.questions.push(q);else next.questions[i]=q;await persist(next,'Đã lưu câu hỏi và cập nhật bộ trình chiếu.');dirty=false;edit(q);}catch(e){error(e.message);}
};
$('#search').oninput=renderList;$('#filter-type').onchange=renderList;
$('#new-question').onclick=()=>{if(canDiscard()){clearEditor();form.elements.prompt.focus();}};$('#cancel-edit').onclick=()=>{if(canDiscard())clearEditor();};
async function move(id,target){const next=clone(data),i=next.questions.findIndex(q=>q.id===id);if(target<0||target>=next.questions.length||target===i){renderList();return;}next.questions.splice(target,0,next.questions.splice(i,1)[0]);try{await persist(next,'Đã cập nhật thứ tự trình chiếu.');}catch{}renderList();}
$('#question-list').onclick=e=>{const row=e.target.closest('[data-id]'),button=e.target.closest('[data-action]');if(!row||!button||busy)return;const id=row.dataset.id,i=data.questions.findIndex(q=>q.id===id);if(button.dataset.action==='edit')edit(data.questions[i]);if(button.dataset.action==='up')move(id,i-1);if(button.dataset.action==='down')move(id,i+1);if(button.dataset.action==='delete'){deleteId=id;$('#delete-summary').textContent=data.questions[i].prompt;$('#delete-dialog').showModal();}};
$('#question-list').onchange=async e=>{const row=e.target.closest('[data-id]');if(!row||busy)return;const id=row.dataset.id;if(e.target.matches('.toggle-enabled')){const next=clone(data);next.questions.find(q=>q.id===id).enabled=e.target.checked;try{await persist(next,'Đã cập nhật câu hỏi hiển thị.');if(selectedID()===id)form.elements.enabled.checked=next.questions.find(q=>q.id===id).enabled;}catch{}renderList();}if(e.target.matches('.position')){const n=Number(e.target.value);if(!Number.isInteger(n)||n<1||n>data.questions.length){status('Vị trí phải nằm trong danh sách câu hỏi.',true);renderList();return;}move(id,n-1);}};
$('#confirm-delete').onclick=async()=>{const next=clone(data);next.questions=next.questions.filter(q=>q.id!==deleteId);try{await persist(next,'Đã xóa câu hỏi.');if(selectedID()===deleteId)clearEditor();renderList();$('#delete-dialog').close();}catch(e){$('#delete-dialog').close();error(e.message);}};
$('#cancel-delete').onclick=()=>$('#delete-dialog').close();
$('#settings-form').onsubmit=async e=>{e.preventDefault();const next=clone(data);next.title=e.target.elements.title.value.trim();try{await persist(next,'Đã lưu tên buổi thi.');}catch{}};
$('#type-engine').innerHTML=TYPES.map(t=>`<option value="${t.engine}">${h(t.label)}</option>`).join('');
$('#type-form').onsubmit=async e=>{e.preventDefault();const label=e.target.elements.label.value.trim();if(data.types.some(t=>t.label.toLocaleLowerCase()===label.toLocaleLowerCase()))return status('Tên dạng câu hỏi này đã tồn tại.',true);const next=clone(data);next.types.push({id:uid(),label,engine:e.target.elements.engine.value});try{await persist(next,`Đã thêm dạng “${label}”.`);fillTypes();e.target.reset();}catch{}};
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`giaoly-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Đã xuất bộ câu hỏi đang lưu. Nội dung chưa bấm Lưu câu hỏi không nằm trong file.');};
$('#import').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>4000000)throw new Error('File không được lớn hơn 4 MB.');imported=validateData(JSON.parse(await file.text()));$('#import-summary').textContent=`“${imported.title}” · ${imported.questions.length} câu hỏi · ${imported.types.length} dạng.`;$('#import-dialog').showModal();}catch(err){status(`Không nhập được: ${err.message}`,true);}};
$('#confirm-import').onclick=async()=>{try{await persist(clone(imported),'Đã nhập và đồng bộ bộ câu hỏi.');$('#settings-form').elements.title.value=data.title;fillTypes();clearEditor();$('#import-dialog').close();}catch(e){$('#import-dialog').close();error(e.message);}};$('#cancel-import').onclick=()=>$('#import-dialog').close();
async function start(){try{const result=await loadAdmin();data=result.data;revision=result.revision;$('#admin-content').hidden=false;$('#login-panel').hidden=true;$('#settings-form').elements.title.value=data.title;$('#account-label').textContent=demo?'Chế độ thử trên máy':getSession()?.user?.email||'Quản trị viên';$('#logout').hidden=demo;fillTypes();clearEditor();status(demo?'Đang thử nghiệm. Dữ liệu này không được công bố lên website.':'Đã tải dữ liệu mới nhất.');}catch(e){$('#login-panel').hidden=false;$('#admin-content').hidden=true;status(e.message,true);}}
$('#login-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;b.textContent='Đang đăng nhập…';$('#login-error').hidden=true;try{await login(e.target.elements.email.value.trim(),e.target.elements.password.value);e.target.elements.password.value='';await start();}catch(err){$('#login-error').hidden=false;$('#login-error').textContent=err.message;}finally{b.disabled=false;b.textContent='Đăng nhập';}};
$('#logout').onclick=async()=>{if(busy)return status('Đang lưu, vui lòng chờ.');if(!canDiscard())return;try{await logout();}catch{}dirty=false;data=null;$('#admin-content').hidden=true;$('#login-panel').hidden=false;$('#account-label').textContent='';status('Đã đăng xuất.');};
window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
$('#register').onclick=async()=>{const f=$('#login-form');if(!f.reportValidity())return;const buttons=[...f.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);$('#login-error').hidden=true;try{const signedIn=await signup(f.elements.email.value.trim(),f.elements.password.value);f.elements.password.value='';if(signedIn)await start();else status('Kiểm tra hộp thư để xác nhận tài khoản, sau đó đăng nhập.');}catch(e){$('#login-error').hidden=false;$('#login-error').textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);}};
$('#forgot-password').onclick=async()=>{const email=$('#login-form').elements.email;if(!email.reportValidity())return;$('#forgot-password').disabled=true;try{await recover(email.value.trim());status('Nếu email hợp lệ, bạn sẽ nhận được liên kết đặt lại mật khẩu.');}catch(e){status(e.message,true);}finally{$('#forgot-password').disabled=false;}};
$('#password-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await updatePassword(e.target.elements.password.value);e.target.reset();$('#password-dialog').close();await start();status('Đã đổi mật khẩu.');}catch(err){$('#password-error').hidden=false;$('#password-error').textContent=err.message;}finally{b.disabled=false;}};
let needsPassword=false;try{if(configured)needsPassword=await acceptCallback();}catch(e){status(e.message,true);}
if(needsPassword)$('#password-dialog').showModal();
if(demo){$('#cloud-notice').textContent='Chế độ thử nghiệm: lưu riêng trên máy, không thay đổi dữ liệu trực tuyến.';document.querySelectorAll('a[href="./"]').forEach(a=>a.href='./?demo=1');start();}else if(!configured){$('#cloud-notice').textContent='Đang thiết lập kết nối cơ sở dữ liệu. Trang quản trị sẽ hoạt động sau khi cấu hình Supabase hoàn tất.';status('Chưa kết nối cơ sở dữ liệu.');}else if(getSession())start();else $('#login-panel').hidden=false;
